### ISSUE TITLE
Branch information on specific location

### ISSUE THREAD

**Issue by sarslanoglu** [enderahmetyurt/turkish_banks#5]
Can we add something like

- Is there any akbank branch in kilyos, if true get info else return a message like 'Aradığınız bölgede bu bankaya ait şube bulunamadı'

- Bank branches in şişli. How many banks and their branches are in şişli. Return message can be 'Şişli bölgesinde 24 farklı bankaya ait 135 şube bulundu.' or we can try to return a array of found objects?

Any thoughts @enderahmetyurt ?

**Comment by enderahmetyurt** [comment]
how can we get the location information? Data is very dirty and it has not a standart unfortunately It should be a little bit hard.
